name: Merge DTDL sources

on:
  push:
    branches: [ "feature-CI" ]
    paths:
      - "Source"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build DTDL Merger
      run: dotnet build ./Tools/DTDLMerger/
    - name: Run DTDL Merger on REC DTDLv2
      run: dotnet run --project ./Tools/DTDLMerger/ ./Source/DTDLv2/ > ./RealEstateCore.DTDLv2.jsonld
    - name: 'Commit merged output'
      run: |
        git config user.name "Karl Hammar"
        git config user.email "hammar@users.noreply.github.com"
        git add .
        git commit -m "Automatically merged sources."
        git push
