name: Validate DTDL sources

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"
    paths:
      - "Source/DTDL**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Clone DTDL Validator
      run: git clone https://github.com/Azure-Samples/DTDL-Validator.git
    - name: Build DTDL Validator
      run: dotnet build ./DTDL-Validator/DTDLValidator-Sample/
    - name: Run DTDL Validator on REC DTDLv2
      run: dotnet run --project ./DTDL-Validator/DTDLValidator-Sample/DTDLValidator/ --recursive true --directory ./Source/DTDLv2/